### ISSUE TITLE
Creating Tickets

### ISSUE THREAD

**Issue by mikebronner** [BeSnappy/api-docs#1]
Would love to see an API entry-point for creating tickets, ala:

POST /ticket

This might be useful for letting 3rd-party apps hook into the workflow, like Mandrill, etc.

**Comment by ianlandsman** [comment]
Hi Mike you can, it's just not called /tickets it's via the /note endpoint.

https://github.com/BeSnappy/api-docs#adding-a-note

**Comment by mikebronner** [comment]
Thank you! I didn't know what the distinction was. :) Setting up Mandrill now SWEEEEEET! :)
