### ISSUE TITLE
Connected Account Profile Information?

### ISSUE THREAD

**Issue by btamilio** [BeSnappy/api-docs#2]
Hi, maybe I missed it in the API docs, but is there a way to get the profile information of the user authenticated and connected to your service via the API? (ie: name, timezone, etc). If not, would you consider it?

I'm aware of /accounts and /accounts/X/staff of course -- and perhaps I'm misunderstanding the data model -- but my assumption is that an API Key is specific to a login/user, and that an individual user can belong to multiple accounts. Knowing "whoami", or having a way to make a relationship with the connected user and the data from /account/X/staff (etc), could be very useful for a variety of purposes for the application making the connection on behalf of the user (feel free to contact me if you'd like more info there).

Anyway, If I've totally missed the connection I'm looking for in the API, my apologies. Otherwise, thanks for considering, and either way, for such a fantastic product! :)

**Comment by ianlandsman** [comment]
Hi!

That's an interesting idea. Currently there's not a way to get meta info on the user but that's something we'll consider as a future enhancement.

Thanks!
